version: '3.8'

services:
  # Nacos注册中心
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: smart-nacos
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    networks:
      - smart-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: smart-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=smart_boot3
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smart-network

  # Redis缓存
  redis:
    image: redis:7.0
    container_name: smart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smart-network

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: smart-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - smart-network

  # API网关
  smart-gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    container_name: smart-gateway
    ports:
      - "8080:8080"
    depends_on:
      - nacos
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - smart-network

  # 认证服务
  smart-auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    container_name: smart-auth
    ports:
      - "8081:8081"
    depends_on:
      - nacos
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=smart_boot3
      - MYSQL_USERNAME=nacos
      - MYSQL_PASSWORD=nacos
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - smart-network

  # 系统管理服务
  smart-system:
    build:
      context: .
      dockerfile: docker/Dockerfile.system
    container_name: smart-system
    ports:
      - "8082:8082"
    depends_on:
      - nacos
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=smart_boot3
      - MYSQL_USERNAME=nacos
      - MYSQL_PASSWORD=nacos
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - smart-network

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

networks:
  smart-network:
    driver: bridge
